contracts:
  eosio.system:
    code_path: ~/bin/eos-bios-launch-data/contracts/eosio.system.wasm
    abi_path: ~/bin/eos-bios-launch-data/contracts/eosio.system.abi
  eosio.bios:
    code_path: ~/bin/eos-bios-launch-data/contracts/eosio.bios.wasm
    abi_path: ~/bin/eos-bios-launch-data/contracts/eosio.bios.abi
  eosio.msig:
    code_path: ~/bin/eos-bios-launch-data/contracts/eosio.msig.wasm
    abi_path: ~/bin/eos-bios-launch-data/contracts/eosio.msig.abi
  eosio.token:
    code_path: ~/bin/eos-bios-launch-data/contracts/eosio.token.wasm
    abi_path: ~/bin/eos-bios-launch-data/contracts/eosio.token.abi

opening_balances:
  snapshot_path: /home/ubuntu/bin/eos-bios-launch-data/snapshot/snapshot_290.csv

producer:
  my_account: eosdublin
  api_address: http://testnet.eosdublin.io
  secret_p2p_address: testnet.eosdublin.io:9876
  wallet_address: http://localhost:6667
  block_signing_public_key: EOS594XCjRRqtCKDT5FsYScB5wHkzmhUCALZc2pYp2zYpJQ2dTTYX

my_parameters:
  base_per_transaction_net_usage: 100
  base_per_transaction_cpu_usage: 500
  base_per_action_cpu_usage: 1000
  base_setcode_cpu_usage: 2097152  # 2 * 1024 * 1024 // overbilling cpu usage for setcode to cover incidental
  per_signature_cpu_usage: 100000
  per_lock_net_usage: 32
  context_free_discount_cpu_usage_num: 20
  context_free_discount_cpu_usage_den: 100
  max_transaction_cpu_usage: 10485760  # 10 * 1024 * 1024
  max_transaction_net_usage: 102400  # 100 * 1024

  max_block_cpu_usage: 104857600  # 100 * 1024 * 1024; at 500ms blocks and 20000instr trx, this enables ~10,000 TPS burst
  target_block_cpu_usage_pct: 1000  # 10%, 2 decimal places
  max_block_net_usage: 1048576
  target_block_net_usage_pct: 1000  # 10%, 2 decimal places

  max_transaction_lifetime: 3600
  max_transaction_exec_time: 0  # unused?!
  max_authority_depth: 6
  max_inline_depth: 4
  max_inline_action_size: 4096
  max_generated_transaction_count: 16

  max_storage_size: 10485760  # 10 * 1024 * 1024
  percent_of_max_inflation_rate: 10000  # percent, with 2 dec places.
  storage_reserve_ratio: 1000  # ratio * 1000

# ENCRYPTION NOT YET IMPLEMENTED!
pgp:
  program: gpg  # or keybase ?
  path: /usr/bin/gpg  # Make sure your keys are in there.

hooks:
  init:
    exec: ~/bin/eos-bios-launch-data/hooks/init.sh
  start_bios_boot:
    exec: ~/bin/eos-bios-launch-data/hooks/start_bios_boot.sh
  connect_as_abp:
    exec: ~/bin/eos-bios-launch-data/hooks/connect_as_abp.sh
  connect_as_participant:
    exec: ~/bin/eos-bios-launch-data/hooks/connect_as_participant.sh
  publish_kickstart_data:
    exec: ~/bin/eos-bios-launch-data/hooks/publish_kickstart_data.sh
  done:
    exec: ~/bin/eos-bios-launch-data/hooks/done.sh

# NOTE: take these out for production !

debug:
  no_shuffle: true
  enrich_producers: true
  keep_system_account: true
